apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      serviceAccountName: prometheus
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
            - '--storage.tsdb.retention=6h'
            - '--storage.tsdb.path=/data'
            - '--config.file=/etc/prometheus/prometheus.yml'
          ports:
            - name: web
              containerPort: 9090
          volumeMounts:
            - name: prometheus-userconfig-volume
              mountPath: /etc/prometheus
            - name: prometheus
              mountPath: /data
      restartPolicy: Always

      volumes:
        - name: prometheus-userconfig-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf

        - name: prometheus
          persistentVolumeClaim:
            claimName: prometheus