apiVersion: v1
kind: Service
metadata:
  name: prometheus
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '9090'
    nx: |-
      - name: prometheus
        direction: L2C
        remoteport: "9090"
        localport: "9090"
        localaddr: prometheus

spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090