apiVersion: v1
kind: Service
metadata:
  name: sample-rev
  namespace: netmux
  labels:
    app: netmux
  annotations:
    nx: |-
      - localport: "8081"
        name: sample-rev
        direction: C2L
        auto: false
        proto: tcp
        localaddr: 127.0.0.1
spec:
  ports:
    - port: 8081
  selector:
    app: netmux