apiVersion: v1
kind: Service
metadata:
  name: sample-rev
  namespace: netmux
  annotations:
    nx: |-
      - localPort: "8082"
        name: sample-rev
        direction: C2L
        auto: false
        proto: tcp
        localAddr: 127.0.0.1
spec:
  ports:
    - port: 8082
      name: sample-rev
      protocol: TCP
      targetPort: 8082
  selector:
    app: netmux