{
 "title": "Netmux - Overview",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Bridge",
    "query": {
     "query": "label_values(netmux_bridges_added,bridge)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Conn Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Daemons",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "netmux_netmux_ndaemons", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "netmux_netmux_nclients{bridge=~\"$Bridge\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Bytes/Sec - Container to Local",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "netmux_netmux_c2lbytes{bridge=~\"$Bridge\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes/Sec -  Local to Container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "netmux_netmux_l2cbytes{bridge=~\"$Bridge\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bridges",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bridges Added",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      { "expr": "netmux_bridges_added", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Bridges Removed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      { "expr": "netmux_bridges_removed", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Bridges Modified",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "targets": [
      { "expr": "netmux_bridges_modified", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}